import { Food } from '../types/food.type';
import { FoodCategory, MeasurementUnit } from '../utils/enum/food.enum';

const NOW = new Date('2025-03-01T02:53:06+01:00');

// Images disponibles
const FOOD_IMAGES = {
    ALMOND: require('../assets/images/foods/almonds.jpg'),
    AVOCADO: require('../assets/images/foods/avocado.jpg'),
    BANANA: require('../assets/images/foods/banana.jpg'),
    BROWN_RICE: require('../assets/images/foods/brown-rice.jpg'),
    CHICKEN: require('../assets/images/foods/chicken.webp'),
    EGG: require('../assets/images/foods/egg.jpg'),
    YOGURT: require('../assets/images/foods/greek-yogurt.jpg'),
    QUINOA: require('../assets/images/foods/quinoa.jpg'),
    RICE: require('../assets/images/foods/rice.jpg'),
    SALMON: require('../assets/images/foods/salmon.jpg'),
    SWEET_POTATO: require('../assets/images/foods/sweet-potato.jpg')
};

export const exampleFoods: Food[] = [
    // Céréales et Féculents
    {
        id: 'f001',
        name: 'Semoule Fine',
        description: 'Semoule de blé dur fine',
        calories: 360,
        protein: 12,
        carbs: 73,
        fats: 1,
        portion: 100,
        servingSize: 60,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.GRAINS,
        imageUrl: FOOD_IMAGES.BROWN_RICE,
        allergens: ['GLUTEN'],
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f002',
        name: 'Riz Japonais',
        description: 'Riz blanc court japonais',
        calories: 130,
        protein: 2.5,
        carbs: 28,
        fats: 0.3,
        portion: 100,
        servingSize: 75,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.GRAINS,
        imageUrl: FOOD_IMAGES.RICE,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f003',
        name: 'Spaghetti',
        description: 'Pâtes longues de blé dur',
        calories: 157,
        protein: 5.8,
        carbs: 31,
        fats: 0.9,
        portion: 100,
        servingSize: 80,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.GRAINS,
        imageUrl: FOOD_IMAGES.QUINOA,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },

    // Protéines
    {
        id: 'f101',
        name: 'Agneau Épaule',
        description: 'Épaule d\'agneau fraîche',
        calories: 220,
        protein: 18,
        carbs: 0,
        fats: 17,
        portion: 100,
        servingSize: 150,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.PROTEIN,
        imageUrl: FOOD_IMAGES.CHICKEN,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f102',
        name: 'Poulet Grillé',
        description: 'Filet de poulet grillé sans peau',
        calories: 165,
        protein: 31,
        carbs: 0,
        fats: 3.6,
        portion: 100,
        servingSize: 120,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.PROTEIN,
        imageUrl: FOOD_IMAGES.CHICKEN,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f103',
        name: 'Saumon Cru',
        description: 'Saumon frais qualité sushi',
        calories: 208,
        protein: 20,
        carbs: 0,
        fats: 13,
        portion: 100,
        servingSize: 100,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.PROTEIN,
        imageUrl: FOOD_IMAGES.SALMON,
        allergens: ['FISH'],
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f104',
        name: 'Pancetta',
        description: 'Poitrine de porc séchée italienne',
        calories: 380,
        protein: 13,
        carbs: 0,
        fats: 37,
        portion: 100,
        servingSize: 30,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.PROTEIN,
        imageUrl: FOOD_IMAGES.CHICKEN,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },

    // Légumes
    {
        id: 'f201',
        name: 'Carottes',
        description: 'Carottes fraîches',
        calories: 41,
        protein: 0.9,
        carbs: 10,
        fats: 0.2,
        portion: 100,
        servingSize: 100,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.VEGETABLES,
        imageUrl: FOOD_IMAGES.SWEET_POTATO,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f202',
        name: 'Pois Chiches Cuits',
        description: 'Pois chiches cuits à l\'eau',
        calories: 164,
        protein: 8.9,
        carbs: 27,
        fats: 2.6,
        portion: 100,
        servingSize: 100,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.VEGETABLES,
        imageUrl: FOOD_IMAGES.SWEET_POTATO,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f203',
        name: 'Navets',
        description: 'Navets frais',
        calories: 28,
        protein: 0.9,
        carbs: 6.4,
        fats: 0.1,
        portion: 100,
        servingSize: 100,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.VEGETABLES,
        imageUrl: FOOD_IMAGES.SWEET_POTATO,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f204',
        name: 'Courgettes',
        description: 'Courgettes fraîches',
        calories: 17,
        protein: 1.2,
        carbs: 3.1,
        fats: 0.3,
        portion: 100,
        servingSize: 100,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.VEGETABLES,
        imageUrl: FOOD_IMAGES.SWEET_POTATO,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f205',
        name: 'Laitue Romaine',
        description: 'Laitue romaine fraîche',
        calories: 17,
        protein: 1.2,
        carbs: 3.3,
        fats: 0.3,
        portion: 100,
        servingSize: 50,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.VEGETABLES,
        imageUrl: FOOD_IMAGES.SWEET_POTATO,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f206',
        name: 'Avocat',
        description: 'Avocat mûr',
        calories: 160,
        protein: 2,
        carbs: 8.5,
        fats: 14.7,
        portion: 100,
        servingSize: 50,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.VEGETABLES,
        imageUrl: FOOD_IMAGES.AVOCADO,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },

    // Produits Laitiers
    {
        id: 'f301',
        name: 'Parmesan',
        description: 'Parmesan Reggiano AOP râpé',
        calories: 431,
        protein: 38,
        carbs: 4.1,
        fats: 29,
        portion: 100,
        servingSize: 30,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.DAIRY,
        imageUrl: FOOD_IMAGES.YOGURT,
        allergens: ['MILK'],
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f302',
        name: 'Œufs',
        description: 'Œufs frais entiers',
        calories: 155,
        protein: 13,
        carbs: 1.1,
        fats: 11,
        portion: 100,
        servingSize: 50,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.DAIRY,
        imageUrl: FOOD_IMAGES.EGG,
        allergens: ['EGGS'],
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },

    // Condiments et Sauces
    {
        id: 'f401',
        name: 'Sauce Soja',
        description: 'Sauce soja traditionnelle japonaise',
        calories: 53,
        protein: 5.6,
        carbs: 5.6,
        fats: 0,
        portion: 100,
        servingSize: 15,
        unit: MeasurementUnit.MILLILITER,
        category: FoodCategory.CONDIMENTS,
        imageUrl: FOOD_IMAGES.BANANA,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f402',
        name: 'Huile d\'Olive',
        description: 'Huile d\'olive extra vierge',
        calories: 884,
        protein: 0,
        carbs: 0,
        fats: 100,
        portion: 100,
        servingSize: 15,
        unit: MeasurementUnit.MILLILITER,
        category: FoodCategory.CONDIMENTS,
        imageUrl: FOOD_IMAGES.ALMOND,
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    },
    {
        id: 'f403',
        name: 'Sauce César',
        description: 'Sauce césar maison',
        calories: 429,
        protein: 2.8,
        carbs: 1.3,
        fats: 45,
        portion: 100,
        servingSize: 30,
        unit: MeasurementUnit.GRAM,
        category: FoodCategory.CONDIMENTS,
        imageUrl: FOOD_IMAGES.YOGURT,
        allergens: ['MILK'],
        verified: true,
        createdAt: NOW,
        updatedAt: NOW
    }
];
