import { Food } from '@/types/food.type';
import { AllergenType, CookingMethod, CuisineType, MeasurementUnit, SpiceLevel } from '@/utils/enum/food.enum';

export const foodExamples: Food[] = [
    {
        id: '1',
        name: 'Poulet (Blanc)',
        calories: 165,
        protein: 31,
        carbs: 0,
        fats: 3.6,
        category: 'PROTEIN',
        portion: 100,
        measurementUnit: MeasurementUnit.GRAM,
        cookingMethod: CookingMethod.GRILLING,
        cuisineType: CuisineType.ARABIC,
        allergens: [],
        spiceLevel: SpiceLevel.NONE,
        unit: 'g',
        image: require('@/assets/images/foods/chicken.webp'),
    },
    {
        id: '2',
        name: 'Riz Brun',
        calories: 216,
        protein: 5,
        carbs: 45,
        fats: 1.8,
        category: 'CARBS',
        portion: 100,
        measurementUnit: MeasurementUnit.GRAM,
        cookingMethod: CookingMethod.BOILING,
        cuisineType: CuisineType.CHINESE,
        allergens: [],
        spiceLevel: SpiceLevel.NONE,
        unit: 'g',
        image: require('@/assets/images/foods/brown-rice.jpg'),
    },
    {
        id: '3',
        name: 'Saumon',
        calories: 208,
        protein: 22,
        carbs: 0,
        fats: 13,
        category: 'PROTEIN',
        portion: 100,
        measurementUnit: MeasurementUnit.GRAM,
        cookingMethod: CookingMethod.BAKING,
        cuisineType: CuisineType.ARABIC,
        allergens: [AllergenType.FISH],
        spiceLevel: SpiceLevel.MILD,
        unit: 'g',
        image: require('@/assets/images/foods/salmon.jpg'),
    },
    {
        id: '4',
        name: 'Avocat',
        calories: 160,
        protein: 2,
        carbs: 8.5,
        fats: 14.7,
        category: 'FATS',
        portion: 100,
        measurementUnit: MeasurementUnit.GRAM,
        cookingMethod: CookingMethod.RAW,
        cuisineType: CuisineType.MEXICAN,
        allergens: [],
        spiceLevel: SpiceLevel.NONE,
        unit: 'g',
        image: require('@/assets/images/foods/avocado.jpg'),
    },
    {
        id: '5',
        name: 'Patate Douce',
        calories: 86,
        protein: 1.6,
        carbs: 20,
        fats: 0.1,
        category: 'CARBS',
        portion: 100,
        measurementUnit: MeasurementUnit.GRAM,
        cookingMethod: CookingMethod.BAKING,
        cuisineType: CuisineType.AMERICAN,
        allergens: [],
        spiceLevel: SpiceLevel.NONE,
        unit: 'g',
        image: require('@/assets/images/foods/sweet-potato.jpg'),
    },
    {
        id: '6',
        name: 'Oeuf',
        calories: 155,
        protein: 13,
        carbs: 1.1,
        fats: 11,
        category: 'PROTEIN',
        portion: 100,
        measurementUnit: MeasurementUnit.PIECE,
        cookingMethod: CookingMethod.FRYING,
        cuisineType: CuisineType.ARABIC,
        allergens: [AllergenType.EGGS],
        spiceLevel: SpiceLevel.NONE,
        unit: 'piece',
        image: require('@/assets/images/foods/egg.jpg'),
    },
    {
        id: '7',
        name: 'Quinoa',
        calories: 120,
        protein: 4.4,
        carbs: 21.3,
        fats: 1.9,
        category: 'CARBS',
        portion: 100,
        measurementUnit: MeasurementUnit.GRAM,
        cookingMethod: CookingMethod.BOILING,
        cuisineType: CuisineType.MEDITERRANEAN,
        allergens: [],
        spiceLevel: SpiceLevel.NONE,
        unit: 'g',
        image: require('@/assets/images/foods/quinoa.jpg'),
    },
    {
        id: '8',
        name: 'Amandes',
        calories: 579,
        protein: 21.2,
        carbs: 21.7,
        fats: 49.9,
        category: 'FATS',
        portion: 100,
        measurementUnit: MeasurementUnit.GRAM,
        cookingMethod: CookingMethod.RAW,
        cuisineType: CuisineType.MEDITERRANEAN,
        allergens: [AllergenType.TREE_NUTS],
        spiceLevel: SpiceLevel.NONE,
        unit: 'g',
        image: require('@/assets/images/foods/almonds.jpg'),
    },
    {
        id: '9',
        name: 'Yaourt Grec',
        calories: 59,
        protein: 10,
        carbs: 3.6,
        fats: 0.4,
        category: 'PROTEIN',
        portion: 100,
        measurementUnit: MeasurementUnit.GRAM,
        cookingMethod: CookingMethod.RAW,
        cuisineType: CuisineType.MEDITERRANEAN,
        allergens: [AllergenType.MILK],
        spiceLevel: SpiceLevel.NONE,
        unit: 'g',
        image: require('@/assets/images/foods/greek-yogurt.jpg'),
    },
    {
        id: '10',
        name: 'Banane',
        calories: 89,
        protein: 1.1,
        carbs: 22.8,
        fats: 0.3,
        category: 'CARBS',
        portion: 100,
        measurementUnit: MeasurementUnit.PIECE,
        cookingMethod: CookingMethod.RAW,
        cuisineType: CuisineType.AMERICAN,
        allergens: [],
        spiceLevel: SpiceLevel.NONE,
        unit: 'piece',
        image: require('@/assets/images/foods/banana.jpg'),
    },
];
