enum MealUnitEnum {
  GRAMMES = 'GRAMMES',
  MILLILITRES = 'MILLILITRES',
  PIECES = 'PIECES',
}
interface MealEntry {
  name: string;
  unit: MealUnitEnum;
  quantity: number;
  calories: number;
  carbs: number;
  fat: number;
  protein: number;
  image?: string | null;
}

const CondimentsEtSauces: MealEntry[] = [
  {
    name: 'Ail Frais',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 149,
    carbs: 33.06,
    fat: 0.5,
    protein: 6.36,
    image: '../assets/images/seed/condiments_et_sauces/ail_frais.jpg',
  },
  {
    name: 'Anis',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 337,
    carbs: 30.88,
    fat: 15.9,
    protein: 17.6,
    image: '../assets/images/seed/condiments_et_sauces/anis.jpg',
  },
  {
    name: 'Cannelle, Sèche',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 355,
    carbs: 79.8,
    fat: 2.2,
    protein: 4.5,
    image: '../assets/images/seed/condiments_et_sauces/cannelle_seche.jpg',
  },
  {
    name: 'Câpre',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 23,
    carbs: 4.89,
    fat: 0.86,
    protein: 2.36,
    image: '../assets/images/seed/condiments_et_sauces/capre.jpg',
  },
  {
    name: 'Carvi',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 333,
    carbs: 30.65,
    fat: 14.59,
    protein: 19.77,
    image: '../assets/images/seed/condiments_et_sauces/carvi.jpg',
  },
  {
    name: 'Coriandre',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 298,
    carbs: 22.15,
    fat: 17.77,
    protein: 12.37,
    image: '../assets/images/seed/condiments_et_sauces/coriandre.jpg',
  },
  {
    name: 'Cornichon au Vinaigre',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 16,
    carbs: 2.2,
    fat: 0.1,
    protein: 0.7,
    image:
      '../assets/images/seed/condiments_et_sauces/cornichon_au_vinaigre.jpg',
  },
  {
    name: 'Cumin, en Poudre',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 445,
    carbs: 40.0,
    fat: 23.2,
    protein: 19.0,
    image: '../assets/images/seed/condiments_et_sauces/cumin_en_poudre.jpg',
  },
  {
    name: 'Curcuma, en Poudre',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 354,
    carbs: 58.44,
    fat: 9.88,
    protein: 7.83,
    image: '../assets/images/seed/condiments_et_sauces/curcuma_en_poudre.jpg',
  },
  {
    name: 'Curry, en Poudre',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 325,
    carbs: 37.52,
    fat: 13.81,
    protein: 12.66,
    image: '../assets/images/seed/condiments_et_sauces/curry_vainilla.jpg',
  },
  {
    name: 'Gingembre, Moulu',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 347,
    carbs: 64.24,
    fat: 5.95,
    protein: 9.12,
    image: '../assets/images/seed/condiments_et_sauces/gingembre_moulu.jpg',
  },
  {
    name: 'Gingembre, Racine',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 80,
    carbs: 17.77,
    fat: 0.75,
    protein: 1.82,
    image: '../assets/images/seed/condiments_et_sauces/gingembre_racine.jpg',
  },
  {
    name: 'Levure de Bière, Sèche',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 308,
    carbs: 30.85,
    fat: 0.0,
    protein: 49.35,
    image:
      '../assets/images/seed/condiments_et_sauces/levure_de_biere_seche.jpg',
  },
  {
    name: 'Mayonnaise',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 717,
    carbs: 3.9,
    fat: 78.2,
    protein: 1.1,
    image: '../assets/images/seed/condiments_et_sauces/mayonnaise.jpg',
  },
  {
    name: 'Menthe, Fraîche',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 44,
    carbs: 8.41,
    fat: 0.73,
    protein: 3.29,
    image: '../assets/images/seed/condiments_et_sauces/menthe_fraiche.jpg',
  },
  {
    name: 'Menthe, Sèche',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 330,
    carbs: 51.0,
    fat: 2.8,
    protein: 25.2,
    image: '../assets/images/seed/condiments_et_sauces/menthe_seche.jpg',
  },
  {
    name: 'Moutarde',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 113,
    carbs: 10.5,
    fat: 6.3,
    protein: 5.5,
    image: '../assets/images/seed/condiments_et_sauces/moutarde.jpg',
  },
  {
    name: 'Noix de Muscade',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 525,
    carbs: 43.71,
    fat: 36.31,
    protein: 5.84,
    image: '../assets/images/seed/condiments_et_sauces/noix_de_muscade.jpg',
  },
  {
    name: 'Piment Rouge, Moulu',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 318,
    carbs: 28.63,
    fat: 17.27,
    protein: 12.01,
    image: '../assets/images/seed/condiments_et_sauces/piment_rouge_moulu.jpg',
  },
  {
    name: 'Poivre Noir, Moulu',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 255,
    carbs: 45.47,
    fat: 3.26,
    protein: 10.95,
    image: '../assets/images/seed/condiments_et_sauces/poivre_noir_moulu.jpg',
  },
  {
    name: 'Vinaigre',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 14,
    carbs: 5.9,
    fat: 0.0,
    protein: 0.0,
    image: '../assets/images/seed/condiments_et_sauces/vinaigre.jpg',
  },
  {
    name: 'Thym',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 276,
    carbs: 43.17,
    fat: 7.43,
    protein: 9.11,
    image: '../assets/images/seed/condiments_et_sauces/thym.jpg',
  },
  {
    name: 'Tomate, Ketchup',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 104,
    carbs: 27.29,
    fat: 0.36,
    protein: 1.52,
    image: '../assets/images/seed/condiments_et_sauces/tomate_ketchup.jpg',
  },
  {
    name: 'Sel, Fin',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 0,
    carbs: 0.0,
    fat: 0.0,
    protein: 0.0,
    image: '../assets/images/seed/condiments_et_sauces/sel_fin.jpg',
  },
];

export default CondimentsEtSauces;
