enum MealUnitEnum {
  GRAMMES = 'GRAMMES',
  MILLILITRES = 'MILLILITRES',
  PIECES = 'PIECES',
}

interface MealEntry {
  name: string;
  unit: MealUnitEnum;
  quantity: number;
  calories: number;
  carbs: number;
  fat: number;
  protein: number;
  image?: string | null;
}

const PoissonsFruitsDeMer: MealEntry[] = [
  {
    name: "Anchois à l'huile_unit_mealunitenum_grammes_quantity_100_calories_210_carbs_0_fat_9_71_protein_28_89_image./assets/images/seed/poissons_et_fruits_de_mer/anchois_a_l'Huile.jpg",
  },
  {
    name: 'Anchois Frais',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 131,
    carbs: 0,
    fat: 4.84,
    protein: 20.35,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/anchois_frais.jpg',
  },
  {
    name: 'Poissans Bleu',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 164,
    carbs: 0,
    fat: 9.19,
    protein: 19.33,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/poissons_bleu.jpg',
  },
  {
    name: 'Calamar Cru',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 92,
    carbs: 3.08,
    fat: 1.38,
    protein: 15.58,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/calamar_cru.jpg',
  },
  {
    name: 'Calamar Sec',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 350,
    carbs: 11.11,
    fat: 5.25,
    protein: 59.24,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/calamar_sec.jpg',
  },
  {
    name: 'Clam Praire ou Palourde Cru',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 74,
    carbs: 2.57,
    fat: 0.97,
    protein: 12.77,
    image:
      '../assets/images/seed/poissons_et_fruits_de_mer/clam_praire_ou_palourde_cru.jpg',
  },
  {
    name: 'Crevette Crue',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 106,
    carbs: 0.91,
    fat: 1.73,
    protein: 20.31,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/crevette_crue.jpg',
  },
  {
    name: 'Hareng Cru',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 158,
    carbs: 0,
    fat: 9.04,
    protein: 17.96,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/hareng_cru.jpg',
  },
  {
    name: 'Loup Cru',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 97,
    carbs: 0,
    fat: 2.33,
    protein: 17.73,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/loup_cru.jpg',
  },
  {
    name: 'Poissons Blanc',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 98,
    carbs: 0,
    fat: 2.04,
    protein: 18.6,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/poissons_blanc.jpg',
  },
  {
    name: 'Maquereau Cru',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 205,
    carbs: 0,
    fat: 13.89,
    protein: 18.6,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/maquereau_cru.jpg',
  },
  {
    name: 'Merlu Cru',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 90,
    carbs: 0,
    fat: 1.31,
    protein: 18.31,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/merlu_cru.jpg',
  },
  {
    name: 'Moule Crue',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 86,
    carbs: 3.69,
    fat: 2.24,
    protein: 11.9,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/moule_crue.jpg',
  },
  {
    name: 'Mulet Cru',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 117,
    carbs: 0,
    fat: 3.79,
    protein: 19.35,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/mulet_cru.jpg',
  },
  {
    name: 'Poulpe Cru',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 82,
    carbs: 2.2,
    fat: 1.04,
    protein: 14.91,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/poulpe_cru.jpg',
  },
  {
    name: 'Poulpe Sèche',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 312,
    carbs: 8.37,
    fat: 3.95,
    protein: 56.69,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/poulpe_seche.jpg',
  },
  {
    name: 'Rascasse Crue',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 94,
    carbs: 0,
    fat: 1.57,
    protein: 18.75,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/rascasse_crue.jpg',
  },
  {
    name: 'Sardine Conserve',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 208,
    carbs: 0,
    fat: 11.45,
    protein: 24.62,
    image:
      '../assets/images/seed/poissons_et_fruits_de_mer/sardine_conserve.jpg',
  },
  {
    name: 'Sardine Crue',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 163,
    carbs: 0,
    fat: 9.0,
    protein: 20.4,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/sardine_crue.jpg',
  },
  {
    name: 'Seiche Crue',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 79,
    carbs: 0.82,
    fat: 0.7,
    protein: 16.24,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/seiche_crue.jpg',
  },
  {
    name: 'Sole Crue',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 91,
    carbs: 0,
    fat: 1.19,
    protein: 18.84,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/sole_crue.jpg',
  },
  {
    name: 'Thon Conserve',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 186,
    carbs: 0,
    fat: 8.08,
    protein: 26.53,
    image: '../assets/images/seed/poissons_et_fruits_de_mer/thon_conserve.jpg',
  },
];

export default PoissonsFruitsDeMer;
