import {
  GenderEnum,
  PhysicalActivityEnum,
} from '@/utils/enum/user-gender-activity.enum';
import {
  GoalEnum,
  HeightUnitEnum,
  WeightUnitEnum,
} from '@/utils/enum/user-details.enum';
import {
  DailyPlanOrmProps,
  IngredientStandardOrmProps,
  MealOrmProps,
  PlanOrmProps,
  UserOrmPros,
} from './schema';
import {
  CuisineTypeEnum,
  MealTypeEnum,
  MealUnitEnum,
} from '@/utils/enum/meal.enum';
import {
  DailyPlanGeneratedWithEnum,
  DayEnum,
  PlanGeneratedWithEnum,
  ProviderEnum,
  RoleEnum,
} from '@/utils/enum/general.enum';

export const usersSeed: Omit<UserOrmPros, 'id' | 'createdAt' | 'updatedAt'>[] =
  [
    {
      name: 'User 1',
      email: 'test1@test.com',
      gender: GenderEnum.MALE,
      height: 160,
      heightUnit: HeightUnitEnum.CM,
      weight: 60,
      weightUnit: WeightUnitEnum.KG,
      profileImage: null,
      physicalActivity: PhysicalActivityEnum.LOW,
      score: 0,
      provider: ProviderEnum.email,
      role: RoleEnum.USER,
      age: 20,
    },
    {
      name: 'Khalil',
      email: 'Khalil@test.com',
      gender: GenderEnum.FEMALE,
      height: 165,
      heightUnit: HeightUnitEnum.CM,
      weight: 55,
      weightUnit: WeightUnitEnum.KG,
      profileImage: null,
      physicalActivity: PhysicalActivityEnum.LOW,
      score: 0,
      provider: ProviderEnum.email,
      role: RoleEnum.USER,
      age: 100,
    },
    {
      name: 'Alice',
      email: 'alice@example.com',
      gender: GenderEnum.FEMALE,
      weight: 55,
      weightUnit: WeightUnitEnum.KG,
      height: 160,
      heightUnit: HeightUnitEnum.CM,
      profileImage: null,
      physicalActivity: PhysicalActivityEnum.MODERATE,
      score: 0,
      provider: ProviderEnum.email,
      role: RoleEnum.USER,
      age: 20,
    },
  ];

export const ingredientsStandardSeed: Omit<
  IngredientStandardOrmProps,
  'id' | 'createdAt' | 'updatedAt'
>[] = [
  {
    name: 'Amidon',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 381,
    carbs: 91.27,
    fat: 0.05,
    protein: 0.26,
    image: null,
  },
  {
    name: 'Biscotte Ordinaire',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 390,
    carbs: 76.60,
    fat: 3.20,
    protein: 12.10,
    image: null,
  },
  {
    name: 'Biscotte Sans Sel',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 390,
    carbs: 76.60,
    fat: 3.20,
    protein: 12.10,
    image: null,
  },
  {
    name: 'Blé en graines',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 327,
    carbs: 65.68,
    fat: 1.54,
    protein: 12.61,
    image: null,
  },
  {
    name: 'Brioche',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 406,
    carbs: 45.80,
    fat: 21.00,
    protein: 8.20,
    image: null,
  },
  {
    name: 'Couscous Sec',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 350,
    carbs: 73.98,
    fat: 1.50,
    protein: 13.44,
    image: null,
  },
  {
    name: 'Farine Blanche',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 364,
    carbs: 74.70,
    fat: 1.20,
    protein: 11.00,
    image: null,
  },
  {
    name: 'Farine D\'orge',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 380,
    carbs: 76.00,
    fat: 4.00,
    protein: 12.00,
    image: null,
  },
    {
    name: 'Maïs, graines sèches',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 365,
    carbs: 74.26,
    fat: 4.74,
    protein: 9.42,
    image: null,
  },
  {
    name: 'Orge Perlé, Cru',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 352,
    carbs: 77.72,
    fat: 1.16,
    protein: 9.91,
    image: null,
  },
  {
    name: 'Pain au chocolat',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 418,
        carbs: 44.05,
        fat: 24.43,
        protein: 8.41,
        image: null,
      },
  {
    name: 'Pain Complet',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 250,
        carbs: 46.40,
        fat: 3.80,
        protein: 10.00,
        image: null,
      },
   {
    name: 'Pain, Tabouna',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 244,
        carbs: 44.53,
        fat: 3.16,
        protein: 8.01,
        image: null,
      },
  {
    name: 'Patate Douce, Crue',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 76,
        carbs: 17.61,
        fat: 0.05,
        protein: 1.57,
        image: null,
      },
  {
    name: 'Pomme de Terre, Frite',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 310,
        carbs: 37.17,
        fat: 15.93,
        protein: 3.54,
        image: null,
      },
   {
    name: 'Aubergine, Crue',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 17,
        carbs: 5.70,
        fat: 0.11,
        protein: 1.01,
        image: null,
      },
  {
    name: 'Betterave Rouge, Crue',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 43,
        carbs: 9.56,
        fat: 0.17,
        protein: 1.61,
        image: null,
      },
  {
    name: 'Carotte, Crue',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 41,
        carbs: 9.51,
        fat: 0.24,
        protein: 0.93,
        image: null,
      },
   {
    name: 'Epinard, Cru',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 23,
        carbs: 3.63,
        fat: 0.39,
        protein: 2.86,
        image: null,
      },
  {
    name: 'Fenouil, Cru',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 31,
        carbs: 7.01,
        fat: 0.20,
        protein: 1.24,
        image: null,
      },
   {
    name: 'Haricot Vert, Cru',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 29,
        carbs: 4.70,
        fat: 0.00,
        protein: 1.81,
        image: null,
      },
  {
     name: 'Laitue, Crue',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 10,
        carbs: 2.09,
        fat: 0.11,
        protein: 1.00,
        image: null,
      },
  {
     name: 'Poivron Vert, Cru',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 20,
        carbs: 4.64,
        fat: 0.17,
        protein: 0.86,
        image: null,
      },
  {
     name: 'Radis, Cru',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 16,
        carbs: 3.40,
        fat: 0.10,
        protein: 0.83,
        image: null,
      },

{
    name: 'Abricot Sec',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 238,
        carbs: 54.82,
        fat: 0.46,
        protein: 3.65,
        image: null,
      },
  {
     name: 'Ananas, Frais',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 52,
        carbs: 11.72,
        fat: 0.12,
        protein: 0.46,
        image: null,
      },
  {
     name: 'Coing, Frais',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 57,
        carbs: 15.30,
        fat: 0.30,
        protein: 0.41,
        image: null,
      },
   {
     name: 'Cerise',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 53,
        carbs: 11.20,
        fat: 0.70,
        protein: 1.90,
        image: null,
      },
   {
     name: 'Melon, Pulpe, Frais',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 28,
        carbs: 6.50,
        fat: 0.14,
        protein: 0.54,
        image: null,
      },
   {
     name: 'Noix de Coco, Fraîche',
        unit: MealUnitEnum.GRAMMES,
        quantity: 100,
        calories: 354,
        carbs: 9.82,
        fat: 33.49,
        protein: 3.33,
        image: null,
      },
];

export const mealsSeed: Omit<
  MealOrmProps,
  'id' | 'creatorId' | 'createdAt' | 'updatedAt'
>[] = [
  {
    type: MealTypeEnum.BREAKFAST,
    name: 'Oatmeal with Fruits',
    description: 'Flocons d\'avoine avec banane et baies',
    cuisine: CuisineTypeEnum.EUROPEAN,
    unit: MealUnitEnum.GRAMMES,
    quantity: 300,
    calories: 382,
    carbs: 70.5,
    fat: 7.3,
    protein: 14.2,
    image: null,
  },
  
];

export const dailyPlanSeed: Omit<
  DailyPlanOrmProps,
  'id' | 'planId' | 'createdAt' | 'updatedAt'
>[] = [
  {
    week: 1,
    calories: 2000,
    carbs: 250,
    fat: 70,
    protein: 150,
    type: DailyPlanGeneratedWithEnum.MANUAL,
    day: DayEnum.MONDAY,
  },
  {
    week: 2,
    calories: 1800,
    carbs: 200,
    fat: 60,
    protein: 140,
    type: DailyPlanGeneratedWithEnum.AI,
    day: DayEnum.WEDNESDAY,
  },
  {
    week: 3,
    calories: 2200,
    carbs: 270,
    fat: 75,
    protein: 160,
    type: DailyPlanGeneratedWithEnum.COMPANY,
    day: DayEnum.FRIDAY,
  },
];

export const planSeed: Omit<
  PlanOrmProps,
  'id' | 'userId' | 'createdAt' | 'updatedAt'
>[] = [
  {
    name: 'Fat Loss Plan',
    goal: GoalEnum.WEIGHT_LOSS,
    unit: WeightUnitEnum.KG,
    initialWeight: 80,
    targetWeight: 70,
    public: true,
    current: true,
    completed: false,
    durationWeeks: 12,
    calories: 1800,
    carbs: 200,
    fat: 50,
    protein: 120,
    type: PlanGeneratedWithEnum.MANUAL,
  },
  {
    name: 'Muscle Gain Plan',
    goal: GoalEnum.GAIN_MUSCLE,
    unit: WeightUnitEnum.LBS,
    initialWeight: 160,
    targetWeight: 180,
    public: false,
    current: false,
    completed: false,
    durationWeeks: 16,
    calories: 2800,
    carbs: 300,
    fat: 80,
    protein: 180,
    type: PlanGeneratedWithEnum.AI,
  },
  {
    name: 'Maintenance Plan',
    goal: GoalEnum.MAINTAIN,
    unit: WeightUnitEnum.KG,
    initialWeight: 70,
    targetWeight: 70,
    public: true,
    current: true,
    completed: true,
    durationWeeks: 8,
    calories: 2200,
    carbs: 250,
    fat: 70,
    protein: 140,
    type: PlanGeneratedWithEnum.MANUAL,
  },
];
