import {
  GenderEnum,
  PhysicalActivityEnum,
} from '@/utils/enum/user-gender-activity.enum';
import {
  GoalEnum,
  HeightUnitEnum,
  WeightUnitEnum,
} from '@/utils/enum/user-details.enum';
import {
  DailyPlanOrmProps,
  IngredientStandardOrmProps,
  MealOrmProps,
  PlanOrmProps,
  UserOrmPros,
} from './schema';
import {
  CuisineTypeEnum,
  MealTypeEnum,
  MealUnitEnum,
} from '@/utils/enum/meal.enum';
import {
  DailyPlanGeneratedWithEnum,
  DayEnum,
  PlanGeneratedWithEnum,
  ProviderEnum,
  RoleEnum,
} from '@/utils/enum/general.enum';

export const usersSeed: Omit<UserOrmPros, 'id' | 'createdAt' | 'updatedAt'>[] =
  [
    {
      name: 'User 1',
      email: 'test1@test.com',
      gender: GenderEnum.MALE,
      height: 160,
      heightUnit: HeightUnitEnum.CM,
      weight: 60,
      weightUnit: WeightUnitEnum.KG,
      profileImage: null,
      physicalActivity: PhysicalActivityEnum.LOW,
      score: 0,
      provider: ProviderEnum.email,
      role: RoleEnum.USER,
      age: 20,
    },
    {
      name: 'Khalil',
      email: 'Khalil@test.com',
      gender: GenderEnum.FEMALE,
      height: 165,
      heightUnit: HeightUnitEnum.CM,
      weight: 55,
      weightUnit: WeightUnitEnum.KG,
      profileImage: null,
      physicalActivity: PhysicalActivityEnum.LOW,
      score: 0,
      provider: ProviderEnum.email,
      role: RoleEnum.USER,
      age: 100,
    },
    {
      name: 'Alice',
      email: 'alice@example.com',
      gender: GenderEnum.FEMALE,
      weight: 55,
      weightUnit: WeightUnitEnum.KG,
      height: 160,
      heightUnit: HeightUnitEnum.CM,
      profileImage: null,
      physicalActivity: PhysicalActivityEnum.MODERATE,
      score: 0,
      provider: ProviderEnum.email,
      role: RoleEnum.USER,
      age: 20,
    },
  ];

export const ingredientsStandardSeed: Omit<
  IngredientStandardOrmProps,
  'id' | 'createdAt' | 'updatedAt'
>[] = [
  {
    name: 'Oats',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 379,
    carbs: 67.0,
    fat: 6.9,
    protein: 13.2,
    image: null,
  },
  {
    name: 'Banana',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 89,
    carbs: 22.8,
    fat: 0.3,
    protein: 1.1,
    image: null,
  },
  {
    name: 'Grilled Chicken',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 165,
    carbs: 0,
    fat: 3.6,
    protein: 31.0,
    image: null,
  },
  {
    name: 'Rice',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 130,
    carbs: 28.0,
    fat: 0.3,
    protein: 2.7,
    image: null,
  },
  {
    name: 'Salmon',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 208,
    carbs: 0,
    fat: 13.0,
    protein: 22.0,
    image: null,
  },
  {
    name: 'Quinoa',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 368,
    carbs: 64.2,
    fat: 6.1,
    protein: 14.1,
    image: null,
  },
  {
    name: 'Avocado',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 160,
    carbs: 8.5,
    fat: 14.7,
    protein: 2,
    image: null,
  },
  {
    name: 'Spinach',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 23,
    carbs: 3.6,
    fat: 0.4,
    protein: 2.9,
    image: null,
  },
  {
    name: 'Sweet Potato',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 86,
    carbs: 20.1,
    fat: 0.1,
    protein: 1.6,
    image: null,
  },
  {
    name: 'Almonds',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 579,
    carbs: 21.6,
    fat: 49.9,
    protein: 21.2,
    image: null,
  },
  {
    name: 'Greek Yogurt',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 59,
    carbs: 3.6,
    fat: 0.4,
    protein: 10.2,
    image: null,
  },
  {
    name: 'Broccoli',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 34,
    carbs: 6.6,
    fat: 0.4,
    protein: 2.8,
    image: null,
  },
  {
    name: 'Eggs',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 155,
    carbs: 1.1,
    fat: 10.6,
    protein: 12.6,
    image: null,
  },
  {
    name: 'Tuna',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 116,
    carbs: 0,
    fat: 0.8,
    protein: 25.5,
    image: null,
  },
  {
    name: 'Lentils',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 116,
    carbs: 20.1,
    fat: 0.4,
    protein: 9,
    image: null,
  },
  {
    name: 'Whole Wheat Bread',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 259,
    carbs: 43.3,
    fat: 3.4,
    protein: 12.6,
    image: null,
  },
  {
    name: 'Cottage Cheese',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 98,
    carbs: 3.4,
    fat: 4.3,
    protein: 11.1,
    image: null,
  },
  {
    name: 'Peanut Butter',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 588,
    carbs: 20,
    fat: 50,
    protein: 25,
    image: null,
  },
  {
    name: 'Olive Oil',
    unit: MealUnitEnum.GRAMMES,
    quantity: 15,
    calories: 119,
    carbs: 0,
    fat: 13.5,
    protein: 0,
    image: null,
  },
  {
    name: 'Blueberries',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 57,
    carbs: 14.5,
    fat: 0.3,
    protein: 0.7,
    image: null,
  },
  {
    name: 'Turkey Breast',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 135,
    carbs: 0,
    fat: 2.9,
    protein: 28.5,
    image: null,
  },
  {
    name: 'Quinoa Flour',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 374,
    carbs: 64.2,
    fat: 6.1,
    protein: 14.1,
    image: null,
  },
  {
    name: 'Kale',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 49,
    carbs: 8.8,
    fat: 0.9,
    protein: 4.3,
    image: null,
  },
  {
    name: 'Chia Seeds',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 486,
    carbs: 42.1,
    fat: 30.7,
    protein: 16.5,
    image: null,
  },
  {
    name: 'Pumpkin Seeds',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 559,
    carbs: 10.7,
    fat: 49.1,
    protein: 30.2,
    image: null,
  },
  {
    name: 'Tofu',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 144,
    carbs: 2.8,
    fat: 8.7,
    protein: 15.8,
    image: null,
  },
  {
    name: 'Chickpeas',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 164,
    carbs: 27.4,
    fat: 2.6,
    protein: 8.9,
    image: null,
  },
  {
    name: 'Beef Steak',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 271,
    carbs: 0,
    fat: 19.5,
    protein: 25.9,
    image: null,
  },
  {
    name: 'Asparagus',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 20,
    carbs: 3.9,
    fat: 0.1,
    protein: 2.2,
    image: null,
  },
  {
    name: 'Bell Pepper',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 31,
    carbs: 6.0,
    fat: 0.3,
    protein: 1.0,
    image: null,
  },
  {
    name: 'Brown Rice',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 111,
    carbs: 23.0,
    fat: 0.9,
    protein: 2.6,
    image: null,
  },
  {
    name: 'Apple',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 52,
    carbs: 13.8,
    fat: 0.2,
    protein: 0.3,
    image: null,
  },
  {
    name: 'Walnuts',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 654,
    carbs: 13.7,
    fat: 65.2,
    protein: 15.2,
    image: null,
  },
  {
    name: 'Coconut Oil',
    unit: MealUnitEnum.GRAMMES,
    quantity: 15,
    calories: 121,
    carbs: 0,
    fat: 13.5,
    protein: 0,
    image: null,
  },
  {
    name: 'Black Beans',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 132,
    carbs: 23.7,
    fat: 0.5,
    protein: 8.9,
    image: null,
  },
  {
    name: 'Strawberries',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 32,
    carbs: 7.7,
    fat: 0.3,
    protein: 0.7,
    image: null,
  },
  {
    name: 'Cauliflower',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 25,
    carbs: 5.0,
    fat: 0.1,
    protein: 1.9,
    image: null,
  },
  {
    name: 'Shrimp',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 99,
    carbs: 0.2,
    fat: 1.7,
    protein: 20.1,
    image: null,
  },
  {
    name: 'Almond Milk',
    unit: MealUnitEnum.MILLILITRES,
    quantity: 100,
    calories: 15,
    carbs: 0.6,
    fat: 1.1,
    protein: 0.5,
    image: null,
  },
  {
    name: 'Flaxseeds',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 534,
    carbs: 28.9,
    fat: 42.2,
    protein: 18.3,
    image: null,
  },
  {
    name: 'Zucchini',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 17,
    carbs: 3.1,
    fat: 0.3,
    protein: 1.2,
    image: null,
  },
  {
    name: 'Cucumber',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 15,
    carbs: 3.6,
    fat: 0.1,
    protein: 0.7,
    image: null,
  },
  {
    name: 'Goji Berries',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 349,
    carbs: 77.1,
    fat: 0.4,
    protein: 14.3,
    image: null,
  },
  {
    name: 'Cashews',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 553,
    carbs: 30.2,
    fat: 43.8,
    protein: 18.2,
    image: null,
  },
  {
    name: 'Tomato',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 18,
    carbs: 3.9,
    fat: 0.2,
    protein: 0.9,
    image: null,
  },
  {
    name: 'Cheddar Cheese',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 402,
    carbs: 1.3,
    fat: 33.1,
    protein: 24.9,
    image: null,
  },
  {
    name: 'Pork Loin',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 143,
    carbs: 0,
    fat: 3.5,
    protein: 26.2,
    image: null,
  },
  {
    name: 'Brussels Sprouts',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 43,
    carbs: 8.9,
    fat: 0.3,
    protein: 3.4,
    image: null,
  },
  {
    name: 'Carrots',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 41,
    carbs: 9.6,
    fat: 0.2,
    protein: 0.9,
    image: null,
  },
  {
    name: 'Honey',
    unit: MealUnitEnum.GRAMMES,
    quantity: 20,
    calories: 61,
    carbs: 16.5,
    fat: 0,
    protein: 0.1,
    image: null,
  },
  {
    name: 'Whey Protein',
    unit: MealUnitEnum.GRAMMES,
    quantity: 30,
    calories: 113,
    carbs: 2.1,
    fat: 1.8,
    protein: 24,
    image: null,
  },
  {
    name: 'Tempeh',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 192,
    carbs: 7.6,
    fat: 10.8,
    protein: 20.3,
    image: null,
  },
  {
    name: 'Mango',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 60,
    carbs: 15,
    fat: 0.4,
    protein: 0.8,
    image: null,
  },
  {
    name: 'Feta Cheese',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 264,
    carbs: 4.1,
    fat: 21.3,
    protein: 14.2,
    image: null,
  },
  {
    name: 'Canned Tuna',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 130,
    carbs: 0,
    fat: 1.5,
    protein: 29,
    image: null,
  },
  {
    name: 'Coconut Milk',
    unit: MealUnitEnum.MILLILITRES,
    quantity: 100,
    calories: 230,
    carbs: 5.5,
    fat: 24,
    protein: 2.3,
    image: null,
  },
  {
    name: 'Seitan',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 370,
    carbs: 14,
    fat: 2,
    protein: 75,
    image: null,
  },
  {
    name: 'Beetroot',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 43,
    carbs: 9.6,
    fat: 0.2,
    protein: 1.6,
    image: null,
  },
  {
    name: 'Tilapia',
    unit: MealUnitEnum.GRAMMES,
    quantity: 100,
    calories: 96,
    carbs: 0,
    fat: 1.7,
    protein: 20.1,
    image: null,
  },
];

export const mealsSeed: Omit<
  MealOrmProps,
  'id' | 'creatorId' | 'createdAt' | 'updatedAt'
>[] = [
  {
    type: MealTypeEnum.BREAKFAST,
    name: 'Oatmeal with Fruits',
    description: 'Flocons d\'avoine avec banane et baies',
    cuisine: CuisineTypeEnum.EUROPEAN,
    unit: MealUnitEnum.GRAMMES,
    quantity: 300,
    calories: 382,
    carbs: 70.5,
    fat: 7.3,
    protein: 14.2,
    image: null,
  },
  {
    type: MealTypeEnum.LUNCH,
    name: 'Grilled Chicken Salad',
    description: 'Salade de poulet grillé avec légumes frais',
    cuisine: CuisineTypeEnum.EUROPEAN,
    unit: MealUnitEnum.GRAMMES,
    quantity: 350,
    calories: 425,
    carbs: 15.4,
    fat: 18.2,
    protein: 52.6,
    image: null,
  },
  {
    type: MealTypeEnum.DINNER,
    name: 'Salmon with Rice',
    description: 'Saumon grillé accompagné de riz et légumes',
    cuisine: CuisineTypeEnum.ASIAN,
    unit: MealUnitEnum.GRAMMES,
    quantity: 350,
    calories: 486,
    carbs: 42.0,
    fat: 16.1,
    protein: 39.2,
    image: null,
  },
];

export const dailyPlanSeed: Omit<
  DailyPlanOrmProps,
  'id' | 'planId' | 'createdAt' | 'updatedAt'
>[] = [
  {
    week: 1,
    calories: 2000,
    carbs: 250,
    fat: 70,
    protein: 150,
    type: DailyPlanGeneratedWithEnum.MANUAL,
    day: DayEnum.MONDAY,
  },
  {
    week: 2,
    calories: 1800,
    carbs: 200,
    fat: 60,
    protein: 140,
    type: DailyPlanGeneratedWithEnum.AI,
    day: DayEnum.WEDNESDAY,
  },
  {
    week: 3,
    calories: 2200,
    carbs: 270,
    fat: 75,
    protein: 160,
    type: DailyPlanGeneratedWithEnum.COMPANY,
    day: DayEnum.FRIDAY,
  },
];

export const planSeed: Omit<
  PlanOrmProps,
  'id' | 'userId' | 'createdAt' | 'updatedAt'
>[] = [
  {
    name: 'Fat Loss Plan',
    goal: GoalEnum.WEIGHT_LOSS,
    unit: WeightUnitEnum.KG,
    initialWeight: 80,
    targetWeight: 70,
    public: true,
    current: true,
    completed: false,
    durationWeeks: 12,
    calories: 1800,
    carbs: 200,
    fat: 50,
    protein: 120,
    type: PlanGeneratedWithEnum.MANUAL,
  },
  {
    name: 'Muscle Gain Plan',
    goal: GoalEnum.GAIN_MUSCLE,
    unit: WeightUnitEnum.LBS,
    initialWeight: 160,
    targetWeight: 180,
    public: false,
    current: false,
    completed: false,
    durationWeeks: 16,
    calories: 2800,
    carbs: 300,
    fat: 80,
    protein: 180,
    type: PlanGeneratedWithEnum.AI,
  },
  {
    name: 'Maintenance Plan',
    goal: GoalEnum.MAINTAIN,
    unit: WeightUnitEnum.KG,
    initialWeight: 70,
    targetWeight: 70,
    public: true,
    current: true,
    completed: true,
    durationWeeks: 8,
    calories: 2200,
    carbs: 250,
    fat: 70,
    protein: 140,
    type: PlanGeneratedWithEnum.MANUAL,
  },
];
